//login
POST https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/auth HTTP/1.1

{
    "username": "lamtvu2",
    "password": "123123"    
}
###
//register
POST https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/users HTTP/1.1

{
    "username": "lamtvu",
    "password": "123123",
    "email": "lamtvu1903@gmail.com"
}

###
//get infor User
GET https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/users HTTP/1.1
Content-Type: application/json
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6ImJlNWJmNWUyNzNlNTk3MGY1MTdlMmFkN2NlOTQ5M2VlYmQyYTBlNjYzZWRjNzVkOWQ3NTViMWE5MDQ1YjNjMmMiLCJ1c2VybmFtZSI6ImxhbXR2dSIsImVtYWlsIjoibGFtdHZ1MTkwQGdtYWlsLmNvbSIsImNyZWF0ZUF0IjoxNjM1NDI3MTQ4MDk1LCJpYXQiOjE2MzU1Nzg0MjksImV4cCI6MTYzNTY2NDgyOX0.qwiWrDfZ2FZ9yPh_e1-SYRrTvm1QTe0bbGj95xdo-Ro

###
//change password
PUT  https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/users HTTP/1.1
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6ImJlNWJmNWUyNzNlNTk3MGY1MTdlMmFkN2NlOTQ5M2VlYmQyYTBlNjYzZWRjNzVkOWQ3NTViMWE5MDQ1YjNjMmMiLCJ1c2VybmFtZSI6ImxhbXR2dSIsImVtYWlsIjoibGFtdHZ1MTkwQGdtYWlsLmNvbSIsImNyZWF0ZUF0IjoxNjM1NDI3MTQ4MDk1LCJpYXQiOjE2MzU1Nzg0MjksImV4cCI6MTYzNTY2NDgyOX0.qwiWrDfZ2FZ9yPh_e1-SYRrTvm1QTe0bbGj95xdo-Ro

{
    "password":"123123123",
    "oldPassword":"thanhlam"
}


//--------------------------------------------------------table-------------------------------------
###
// lay bảng, lấy trang đầu ko truyền cái exlusiveStartKey, muốn lấy dữ liệu trang tiếp nhét cái lastEvaluatedKey từ response vào.
GET  https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/tables?limit=3&exlusiveStartKey=lamtvu2,demo2 HTTP/1.1
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2MzQyMywiZXhwIjoxNjM2NTQ5ODIzfQ.l_YKF0akLpG5zTA35em71SPKdh3mmVcBNhK0k1-CC58

###
// tạo bảng
POST  https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/tables HTTP/1.1
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2MzQyMywiZXhwIjoxNjM2NTQ5ODIzfQ.l_YKF0akLpG5zTA35em71SPKdh3mmVcBNhK0k1-CC58

{
    "tableName":"demo5"
}


###
// xóa bảng
DELETE   https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/tables HTTP/1.1
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2MzQyMywiZXhwIjoxNjM2NTQ5ODIzfQ.l_YKF0akLpG5zTA35em71SPKdh3mmVcBNhK0k1-CC58

{
    "tableName":"demo5"
}


//----------------------------------------------------------data---------------------------------------POScw###

// lay dữ liệu trong bảng
###
GET   https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/data?tableName=demo5&limit=2&exlusiveStartKey HTTP/1.1
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2MzQyMywiZXhwIjoxNjM2NTQ5ODIzfQ.l_YKF0akLpG5zTA35em71SPKdh3mmVcBNhK0k1-CC58

//them dữ liệu trong bảng
###
POST https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/data HTTP/1.1
Authorization:Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJyb2xlIjoxLCJjcmVhdGVBdCI6MTYzNTU3ODM3NjU1MCwidXNlcm5hbWUiOiJsYW10dnUyIiwiZW1haWwiOiJsYW10dnUxOTAzQGdtYWlsLmNvbSIsImtleSI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW14aGJYUjJkVElpTENKamNtVmhkR1ZCZENJNk1UWXpOVFUzT0RNM05qVTFNQ3dpYVdGMElqb3hOak0yTlRNeE1EQXdmUS5kY3I3Z19mNzVaYVBlc25kVnNnZThzWFFIelVSV1Z6dGNkTG93NW50aHBNIiwiaWF0IjoxNjM2NjE1OTY2LCJleHAiOjE2MzY3MDIzNjZ9.lmRWJxbOT6guM0sOmzOPJCSOwQZq-AtGr_7QpWKZGJQ

{
    "tableName":"demo5",
    "item":{
        "name":"lam2tvu",
        "age":"100",
        "data": {
            "a":true,
            "b":true,
            "c":true
        }
    }
}

//thay doi du lieu trong bang
###
// bac buot co _id
PUT https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/data HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2NjQyMywiZXhwIjoxNjM2NTUyODIzfQ.DxE_iRU4XZyFjKJJb5nAI1pfkUl9RHHjYxnqWTB4WFI

{
    "tableName":"demo5",
    "item":{
        "_id":"b41fa025-27ff-41d2-b8cf-8ac1ecbeff49",
        "name":"lamtvu1000",
        "age":"100"
    }
}

###
//xoa du lieu
DELETE  https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/data HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2NjQyMywiZXhwIjoxNjM2NTUyODIzfQ.DxE_iRU4XZyFjKJJb5nAI1pfkUl9RHHjYxnqWTB4WFI

{
    "tableName":"demo5",
    "_id":"b41fa025-27ff-41d2-b8cf-8ac1ecbeff49"
}

//-------------------------------------------------key----------------------------------------------------
//tao key
###
POST  https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/key HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6Ijk2Y2FlMzVjZThhOWIwMjQ0MTc4YmYyOGU0OTY2YzJjZTFiODM4NTcyM2E5NmE2YjgzODg1OGNkZDZjYTBhMWUiLCJ1c2VybmFtZSI6ImxhbXR2dTIiLCJyb2xlIjoxLCJlbWFpbCI6ImxhbXR2dTE5MDNAZ21haWwuY29tIiwiY3JlYXRlQXQiOjE2MzU1NzgzNzY1NTAsImlhdCI6MTYzNjQ2NjQyMywiZXhwIjoxNjM2NTUyODIzfQ.DxE_iRU4XZyFjKJJb5nAI1pfkUl9RHHjYxnqWTB4WFI
//-------------------------------------------------api----------------------------------------------------
//get data
###
POST https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/api?method=get&key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbXR2dTIiLCJjcmVhdGVBdCI6MTYzNTU3ODM3NjU1MCwiaWF0IjoxNjM3MjMzMTk4fQ.yCgqHxjH7hjMqQFWt-cta1fSxvkvzLLOYXWWa73Kdnc

{
    "TableName":"demo5",
    "ProjectionExpression":"#id,#name",
    "FilterExpression":"#age = :yyyy",
    "ExpressionAttributeNames":{
        "#id":"_id",
        "#name":"name",
        "#age":"age"
    },
    "ExpressionAttributeValues":{
        ":yyyy": "100"
    }
}

//delete
###
DELETE https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/api?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbXR2dTIiLCJjcmVhdGVBdCI6MTYzNTU3ODM3NjU1MCwiaWF0IjoxNjM3MjMzMTk4fQ.yCgqHxjH7hjMqQFWt-cta1fSxvkvzLLOYXWWa73Kdnc

{
    "TableName":"demo5",
    "Key":{
        "_id":"a42740e2-857b-41bf-b07f-5d357a9db491"
    }
}

//update
###
PUT https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/api?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbXR2dTIiLCJjcmVhdGVBdCI6MTYzNTU3ODM3NjU1MCwiaWF0IjoxNjM3MjMzMTk4fQ.yCgqHxjH7hjMqQFWt-cta1fSxvkvzLLOYXWWa73Kdnc

{
    "TableName":"demo5",
    "Key":{
        "_id":"ba779cb5-9e6f-4cc0-939c-808654edd452"
    },
    "UpdateExpression":"set #name=:name",
    "ExpressionAttributeNames":{
        "#name": "name"
    },
    "ExpressionAttributeValues":{
        ":name": "aaaaaaa"
    }
}

//create
###
POST https://k9ilwv1dvj.execute-api.us-east-1.amazonaws.com/cloudbe/api?method=create&key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhbXR2dTIiLCJjcmVhdGVBdCI6MTYzNTU3ODM3NjU1MCwiaWF0IjoxNjM3MjMzMTk4fQ.yCgqHxjH7hjMqQFWt-cta1fSxvkvzLLOYXWWa73Kdnc

{
    "TableName":"demo5",
    "Item":{
        "name":"create new",
        "age": "100",
        "a":"b"
    }
}